# Generated by Django 3.0.3 on 2020-05-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
