# Generated by Django 3.0.3 on 2020-05-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_auto_20200526_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_favorite',
        ),
    ]
